driver:
  name: vagrant

driver_config:
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  attributes:
    docker:
      container_cmd_timeout: 30

verifier:
  name: inspec

platforms:
- name: centos-6.8
  run_list:
  - recipe[chef-yum-docker]

- name: centos-7.2
  run_list:
  - recipe[chef-yum-docker]

- name: fedora-24
  run_list:
  - recipe[yum::dnf_yum_compat]
  - recipe[chef-yum-docker]

- name: debian-7.11
  run_list:
  - recipe[apt]
  - recipe[chef-apt-docker]

- name: debian-8.5
  run_list:
  - recipe[apt]
  - recipe[chef-apt-docker]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  - recipe[chef-apt-docker]

- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[chef-apt-docker]

- name: ubuntu-16.04
  run_list:
    - recipe[apt]
  run_list:
  - recipe[apt]
  - recipe[chef-apt-docker]


suites:
#####################################
# docker_installation_tarball resource
#####################################

- name: installation_tarball-1112
  includes: [
    'ubuntu-16.04'
   ]
  attributes:
    docker:
      version: '1.11.2'
  run_list:
  - recipe[docker_test::installation_tarball]

#####################################
# docker_installation_binary resource
#####################################

- name: installation_binary-1112
  includes: [
    'ubuntu-16.04'
   ]
  attributes:
    docker:
      version: '1.10.0'
  run_list:
  - recipe[docker_test::installation_binary]

#####################################
# docker_installation_script resource
#####################################

- name: installation_script_main
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'main'
  run_list:
  - recipe[docker_test::installation_script]

- name: installation_script_test
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'test'
  run_list:
  - recipe[docker_test::installation_script]

- name: installation_script_experimental
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'experimental'
  run_list:
  - recipe[docker_test::installation_script]

######################################
# docker_installation_package resource
######################################

- name: installation_package-1123
  includes: [
    'centos-7.2',
    'debian-7.11',
    'debian-8.5',
    'ubuntu-12.04',
    'ubuntu-14.04',
    'ubuntu-16.04',
    'fedora-24'
   ]
  attributes:
    docker:
      version: '1.12.3'
  run_list:
  - recipe[docker_test::installation_package]

#################################
# docker_service_execute resource
#################################
- name: service-execute
  includes: [
    'ubuntu-16.04',
   ]
  run_list:
  - recipe[docker_test::service_execute]

- name: service-execute-multi
  includes: [
    'ubuntu-16.04',
   ]
  run_list:
  - recipe[docker_test::service_execute_multi]

##################################
# docker_service_sysvinit resource
##################################
- name: service-sysvinit
  includes: [
    'debian-7.11'
   ]
  run_list:
  - recipe[docker_test::service_sysvinit]

- name: service-sysvinit-multi
  includes: [
    'debian-7.11'
   ]
  run_list:
  - recipe[docker_test::service_sysvinit_multi]

#################################
# docker_service_upstart resource
#################################
- name: service-upstart
  includes: [
    'ubuntu-12.04',
    'ubuntu-14.04'
   ]
  run_list:
  - recipe[docker_test::service_upstart]

- name: service-upstart-multi
  includes: [
    'ubuntu-12.04',
    'ubuntu-14.04'
   ]
  run_list:
  - recipe[docker_test::service_upstart_multi]

#################################
# docker_service_systemd resource
#################################
- name: service-systemd
  includes: [
    'centos-7.2',
    'fedora-24',
    'debian-8.5',
    'ubuntu-16.04'
   ]
  run_list:
  - recipe[docker_test::service_systemd]

- name: service-systemd-multi
  includes: [
    'centos-7.2',
    'fedora-24',
    'debian-8.5',
    'ubuntu-16.04'
   ]
  run_list:
  - recipe[docker_test::service_systemd_multi]

#######################
# bulk resource testing
#######################

- name: resources-1123
  includes: [
    'ubuntu-16.04',
    'centos-7.2'
   ]
  attributes:
    docker:
      version: '1.12.3'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::image]
  - recipe[docker_test::container]
  - recipe[docker_test::exec]

- name: network
  includes: [
    'ubuntu-16.04'
   ]
  attributes:
    docker:
      version: '1.11.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::network]

- name: volume
  includes: [
    'ubuntu-16.04'
   ]
  attributes:
    docker:
      version: '1.11.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::volume]

#####################
# docker_service auto
#####################

- name: auto
  includes: [
    'centos-7.2',
    'fedora-24',
    'debian-8.5',
    'ubuntu-12.04',
    'ubuntu-14.04',
    'ubuntu-16.04'
   ]
  run_list:
  - recipe[docker_test::auto]
