---
driver:
  name: dokken
  chef_version: current
  privileged: true
  volumes: [
    '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
    ]

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
  run_list:
  - recipe[chef-apt-docker]

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: centos-6
  driver:
    image: dokken/centos-6
    platform: rhel
    pid_one_command: /sbin/init
  run_list:
    - recipe[chef-yum-docker]

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
  run_list:
    - recipe[chef-yum-docker]

- name: fedora-25
  driver:
    image: dokken/fedora-25
    pid_one_command: /usr/lib/systemd/systemd
  run_list:
    - recipe[chef-yum-docker]

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-17.04
  driver:
    image: dokken/ubuntu-17.04
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

suites:
- name: installation_script_main
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'main'
  run_list:
  - recipe[docker_test::installation_script]

- name: installation_script_test
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'test'
  run_list:
  - recipe[docker_test::installation_script]

- name: installation_script_experimental
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      repo: 'experimental'
  run_list:
  - recipe[docker_test::installation_script]

######################################
# docker_installation_package resource
######################################

- name: installation_package-17031
  includes: [
    'amazonlinux', # for dokken
    ]
  attributes:
    docker:
      version: '17.03.1'
  run_list:
  - recipe[docker_test::installation_package]

- name: installation_package-17062
  includes: [
    'centos-7', # for dokken
    'debian-7', # for dokken
    'debian-8', # for dokken
    'ubuntu-14.04',
    'ubuntu-16.04',
    'ubuntu-17.04',
    'fedora-25',
   ]
  attributes:
    docker:
      version: '17.06.2'
  run_list:
  - recipe[docker_test::installation_package]

#######################
# bulk resource testing
#######################

- name: resources-17062
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      version: '17.06.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::image]
  - recipe[docker_test::container]
  - recipe[docker_test::exec]

- name: network
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      version: '17.06.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::network]

- name: volume
  includes: [
    'ubuntu-16.04',
   ]
  attributes:
    docker:
      version: '17.06.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::volume]

######################################
# service smoke testing
######################################

- name: smoke
  excludes: [
    'centos-6',
    'opensuse-13.2',
    ]
  run_list:
  - recipe[docker_test::smoke]
