---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart
  binds: '/var/run/docker.sock:/var/run/docker.sock'

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install net-tools apt-transport-https
      - RUN /usr/bin/apt-get -y install kmod iptables
  run_list:
  - recipe[chef-apt-docker]

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install net-tools apt-transport-https
      - RUN /usr/bin/apt-get -y install kmod iptables
  run_list:
  - recipe[chef-apt-docker]

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which net-tools

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which net-tools

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install net-tools apt-transport-https
      - RUN /usr/bin/apt-get -y install iptables
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install net-tools apt-transport-https
      - RUN /usr/bin/apt-get -y install kmod iptables
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install net-tools apt-transport-https
      - RUN /usr/bin/apt-get -y install kmod iptables
  run_list:
  - recipe[chef-apt-docker]

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper install -y net-tools

- name: amazonlinux
  driver:
    image: amazonlinux:latest
    pid_one_command: /sbin/init
