AllCops:
  Excludes:
    - test/**
    - vendor/**
    - ruby/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
