---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@8.0.1
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - "default"
          - "installation-package"
          - "installation-tarball"
          - "installation-script"
          - "install-and-stop"
          - "resources"
          - "network"
          - "volume"
          - "registry"
          - "swarm"
          - "smoke"
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0

      - name: Test Kitchen
        uses: actionshub/test-kitchen@3.0.0
        env:
          KITCHEN_LOCAL_YAML: kitchen.exec.yml
        with:
          suite: ${{ matrix.suite }}
          os: "ubuntu-latest"

  final:
    needs: [lint-unit, integration]
    runs-on: ubuntu-latest
    steps:
      - name: Complete
        run: echo "All tests passed"
